baseURL = 'https://petervalkenburg.github.com/'
languageCode = 'nl'
title = "Peter Valkenburg"
timeZone = "Europe/Amsterdam"

[params]
  description = "Portfolio website van Peter Valkenburg"
  title = "Gallerij van Peter"

[module]
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"
